@echo off
echo Starte InventoryPro Analytics...
cd /d "c:\Users\Lucas\Desktop\01_Sören\electron-v1"

echo Stoppe alte Prozesse...
taskkill /f /im electron.exe 2>nul
taskkill /f /im node.exe 2>nul

echo Starte Development-Server und Desktop-App...
npm run dev &

echo Warte 3 Sekunden auf Server-Start...
timeout /t 3 /nobreak >nul

echo Starte Desktop-App...
start /B electron .

echo InventoryPro Analytics wird gestartet...
